### ISSUE TITLE
Add any other sorting algorithm

### ISSUE THREAD

**Issue by diptangsu** [diptangsu/Sorting-Algorithms#1]
Please add any other sorting algorithm that is not present in this repository.
Please also try to update the [TimeTakenToSort.java](https://github.com/diptangsu/Sorting-Algorithms/blob/master/src/TimeTakenToSort.java) file accordingly.
Create a separate branch with the name of the sorting algorithm you want to add.

**Comment by YuechengWu** [comment]
Hi @diptangsu, please allow me to have a crack at this issue, thanks.

**Comment by Rudy-Menekam** [comment]
hello @diptangsu please i need help to update the timetakentosort.java file

**Comment by deepakgangore** [comment]
#10 Pls pull

**Comment by vandanagupta1501** [comment]
is this issue still open

**Comment by diptangsu** [comment]
are there more sorting algorithms?

**Comment by vishnoitanuj** [comment]
Added optimized bubble sort to remove redundancy swaps. Please pull #82
